@baseUrl = http://localhost:3000 

### AppControllerGetHello

# @name AppControllerGetHello
GET {{baseUrl}}

### ManualConceptsController

# @name ManualConceptsControllerHome
GET {{baseUrl}}/manual-concepts